name = "PokemonLean"
version = "0.1.0"
defaultTargets = ["pokemonlean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "PokemonLean"

[[lean_exe]]
name = "pokemonlean"
root = "Main"
